from abc import ABC, abstractmethod
import pandas as pd

@abstractmethod
class Iprimary_moveInterface(ABC):
    def save_id(self, id):
        ...
    def update_name(self, name):
        ...
    def update_nationality(self, nationality):
        ...
    def update_fighting_style(self, fighting_style):
        ...
    def find_by_all(self) -> pd.DataFrame:
        ...