from abc import ABC, abstractmethod
import pandas as pd

@abstractmethod
class Iprimary_skillInterface(ABC):
    def find_by_id(self, id):
        ...
    def find_by_skill_id(self, skill_id):
        ...
    def update_startup_frame(self, startup_frame):
        ...
    def update_On_Hit_frame(self, On_Hit_frame):
        ...
    def update_On_Block_frame(self, On_Block_frame):
        ...
    def find_all(self) -> pd.DataFrame:
        ...