from abc import ABC, abstractmethod

@abstractmethod
class IJoinInterface(ABC):
    def find_character_name(self, character_name):
        ...
    def find_command(self, command):
        ...
    def find_startup_frame(self, startup_frame):
        ...
    def find_On_Hit_frame(self, On_Hit_frame):
        ...
    def find_On_Block_frame(self, On_Block_frame):
        ...