from abc import ABC, abstractmethod

@abstractmethod
class IJoinInterface(ABC):
    def find_fighter_name(self, fighter_name):
        ...
    def find_move_name(self, move_name):
        ...
    def find_command(self, command):
        ...
    def find_startup(self, startup):
        ...
    def find_Hit(self, Hit):
        ...
    def find_Block(self, Block):
        ...
    def find_Counter(self, Counter):
        ...