from abc import ABC, abstractmethod
import pandas as pd

@abstractmethod
class Imove_frameInterface(ABC):
    def save_id(self, id):
        ...
    def update_move_id(self, move_id):
        ...
    def update_startup(self, startup):
        ...
    def update_Hit(self, Hit):
        ...
    def update_Block(self, Block):
        ...
    def update_Counter(self, Counter):
        ...
    def find_all(self) -> pd.DataFrame:
        ...