from abc import ABC, abstractmethod
import pandas as pd

@abstractmethod
class ImoveInterface(ABC):
    def find_by_id(self, id):
        ...
    def update_fighter_id(self, fighter_id):
        ...
    def update_move_name(self, move_name):
        ...
    def update_command(self, command):
        ...
    def find_all(self) -> pd.DataFrame:
        ...